### ISSUE TITLE
[Documentation] `beforeVariants` syntax for Groovy

### ISSUE THREAD

**Issue by BugsBunnyBR** [slackhq/keeper#101]
Hello there, it seems that this

``` groovy
androidComponents {
  beforeVariants { builder ->
    if (shouldRunKeeperOnVariant(builder)) {
      builder.registerExtension(KeeperVariantMarker.class, KeeperVariantMarker.INSTANCE)
    }
  }
}
```

does not work with AGP 7.1.2, but

``` groovy
androidComponents {
  beforeVariants(selector().all()) { builder ->
      // NOTE: You need to define this method or use a build flag, see configuration section.
    if (shouldRunKeeperOnVariant(builder)) {
      builder.registerExtension(KeeperVariantMarker.class, KeeperVariantMarker.INSTANCE)
    }
  }
}

```
works.

Also, it would be great to have in red flashing lights that the default behaviour of just applying the plugin changed in the this section https://slackhq.github.io/keeper/#installation saying that this block of configuration is required. Leaving it in the "Configuration" block makes it seem as optional. 

Thanks for the great library.

**Comment by ZacSweers** [comment]
Wanna send a PR?
