### ISSUE TITLE
Some Keeper rules affect R8 optimization

### ISSUE THREAD

**Issue by mateuszkwiecinski** [slackhq/keeper#106]
**Keeper version:** 0.12.0

We encountered a R8 bug where the following class:
```kotlin
sealed class Foo {
     
     enum class Bar { ... }
     
     internal val Bar.someExtension get() = ...
    
     class Wrapper: Foo {
		enum class Baz {
  			internal val someExtension get() = ...
       	}
     }
}
```
crashes production version of our app with `LinkageError`
>java.lang.LinkageError: Method java.lang.String xxx.yyy.zzz.k2$q1.c(int) overrides final method in class Lxxx.yyy.zzz/k2; (declaration of ‘xxx.yyy.zzz.k2$q1’ appears in base.apk)

We hoped running Espresso tests on an obfuscated variant would prevent us from letting such bugs through. While debugging R8 rules added by Keeper we narrowed it down to: 
```pro
-keep class kotlin.jvm.internal.Intrinsics {
  public static void checkNotNullParameter(java.lang.Object,java.lang.String);
}
```

Keeping the intrinsics, in this particular case, prevents R8 from optimizing enums to Ints, which would normally take place if keeper wasn't applied.

I'm aware of https://issuetracker.google.com/issues/126429384 which forces you to _guess_ the keep rules, but I wonder if they could be fine-tuned so the tested apk resembles the "real" one more. In particular, it seems like since Kotlin intrinsics aren't explicitly called by the test code, it doesn't seem necessary to keep them. Alternatively, is there a way to override Keeper's rules to handle such exceptions manually?

#### Steps to reproduce:

1. Build production apk
2. verify it crashes with R8 bug
3. Build test variant with keeper applied 

#### Expected result:
Test variant should also fail

#### Actual result:
Test variant is obfuscated in a completely different way, diffuse shows +600kb being added to the apk built with keeper enabled. This actually seems like a lot — I'd be hard-pressed to find 600kb of classes used by test code but not by the release apk.
```
          │             compressed             │            uncompressed            
          ├───────────┬───────────┬────────────┼───────────┬───────────┬────────────
 APK      │ old       │ new       │ diff       │ old       │ new       │ diff       
──────────┼───────────┼───────────┼────────────┼───────────┼───────────┼────────────
      dex │   3.6 MiB │   3.7 MiB │ +149.1 KiB │   8.9 MiB │   9.5 MiB │ +606.2 KiB 
     arsc │ 737.2 KiB │ 737.2 KiB │        0 B │ 737.1 KiB │ 737.1 KiB │        0 B 
 manifest │   4.7 KiB │   4.7 KiB │        0 B │  19.6 KiB │  19.6 KiB │        0 B 
      res │   1.3 MiB │   1.3 MiB │        0 B │     2 MiB │     2 MiB │        0 B 
   native │  43.5 KiB │  43.5 KiB │        0 B │    43 KiB │    43 KiB │        0 B 
    asset │ 199.4 KiB │ 199.3 KiB │      -45 B │ 177.6 KiB │ 177.6 KiB │      -45 B 
    other │ 221.3 KiB │ 221.3 KiB │       -7 B │ 449.4 KiB │ 449.4 KiB │        0 B 
──────────┼───────────┼───────────┼────────────┼───────────┼───────────┼────────────
    total │   6.1 MiB │   6.2 MiB │ +149.1 KiB │  12.3 MiB │  12.9 MiB │ +606.2 KiB 
```

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by ZacSweers** [comment]
this is by design, these are rules calculated in order for them to be safely used. If you think the rules generated are sub-optimal, please file a feature request on the R8 issue tracker (as we use their tracereferences CLI under the hood for this).
