### ISSUE TITLE
ClassNotFoundException for MultipleArtifact.ALL_CLASSES_DIR with AGP 8.0.0-alpha09

### ISSUE THREAD

**Issue by alexvanyo** [slackhq/keeper#109]
**Keeper version:** 0.12.0

#### Steps to reproduce:

1. Update AGP to 8.0.0-alpha09
2. `./gradlew tasks`

#### Expected result:

Keeper is initialized correctly

#### Actual result:

`./gradlew tasks` fails with `java.lang.ClassNotFoundException` for `com.android.build.api.artifact.MultipleArtifact$ALL_CLASSES_DIR`

#### Attachments:

`ALL_CLASSES_DIR` was recently removed, as per this commit: https://cs.android.com/android-studio/platform/tools/base/+/8e496713acce67efd36916dfc446333eb12ad4f3

**Comment by ZacSweers** [comment]
Thanks for the report, I'll take a look soon

**Comment by ZacSweers** [comment]
@alexvanyo see details here: https://github.com/slackhq/keeper/pull/117#issuecomment-1435773746. I've published an alpha release with support from that PR as well

**Comment by alexvanyo** [comment]
Late reply, thank you! I was able to update to `0.14.0-alpha04` with AGP `8.0.0-rc01` and run tests with `keeper.disableTestProguardFiles=true` set to true as well.

As a heads up, it looks like `8.1.0` introduces another incompatible change, the latest there doesn't work with Keeper `0.14.0-alpha04`.

**Comment by ZacSweers** [comment]
Lovely. Could you file a separate issue with a trace?

**Comment by alexvanyo** [comment]
Reported #119 with the AGP 8.1.0 issue
