### ISSUE TITLE
Slack keeper plugin is not applied after updating to 0.12.0 or greater than that

### ISSUE THREAD

**Issue by sanjeevirajm** [slackhq/keeper#116]
**Keeper version:** 0.11.0

#### Steps to reproduce:

1. Try using keeper 0.11.0 -> open gradle tasks list -> Keeper tasks would be visible, also keeper folder would be present under intermediates folder
2. Update it to 0.12.0 or 0.13.0, clean build -> keeper won't be present under tasks list or intermediates folder

Expected result: 
Keeper tasks should be visible, intermediates folder should be generated
<img width="486" alt="Screenshot 2023-01-18 at 8 11 21 PM" src="https://user-images.githubusercontent.com/18301181/213201940-b9e82ffb-9057-4ac2-84de-8bd9619803e8.png">
<img width="303" alt="Screenshot 2023-01-18 at 8 17 30 PM" src="https://user-images.githubusercontent.com/18301181/213202187-07c22a3f-b566-4d92-8fa5-b95ae6ed7010.png">

**Comment by sanjeevirajm** [comment]
Tried with Gradle version - 8.0.0-alpha11

**Comment by ZacSweers** [comment]
Per the release notes for 0.12.0, there are new installation instructions to enable keeper. It is not enough to just update the dependency. Please read the release notes.

**Comment by sanjeevirajm** [comment]
Got it. 
Keeper's default behavior with no configuration effectively be a no-op, which isn't what you want!

**Comment by sanjeevirajm** [comment]
Thanks
