### ISSUE TITLE
Task `...AndroidTestClassesForKeeper` uses output of task `...testFixturesJar` without delcaring an explicit dependency

### ISSUE THREAD

**Issue by lwasyl** [slackhq/keeper#122]
### Discussed in https://github.com/slackhq/keeper/discussions/120

I got a minimal repro for the issue I described before, and I believe it's either a bug in Keeper or in AGP. Repro: https://github.com/mateuszkwiecinski/keeper_doesnt_work/tree/a994e5bb5ac1425cd6bce83e74ad21435b642539, sample run: https://github.com/mateuszkwiecinski/keeper_doesnt_work/actions/runs/4891040543/jobs/8731069911, build scan: https://scans.gradle.com/s/nwt2uvrkdlrta. 

Generally it looks like Keeper is analyzing the `testFixtures` jars that are should not be visible to the app in the first place, because they're only `implementation` dependency. Changing the dependency in `ui-testing/build.gradle` to `testFixturesApi testFixtures(project(":testing-common"))` fixes the issue, similarly `testFixturesImplementation project(":testing-common")` works as well. 

<div type='discussions-op-text'>

<sup>Originally posted by **lwasyl** April  6, 2023</sup>
**Keeper version:** 0.13.0 (0.12.0 works fine), AGP 7.4.2

After upgrading to Keeper 0.13.0 I started seeing failures as in the title:

```
* What went wrong:
Some problems were found with the configuration of task ':app:jarStageReleaseTestAndroidTestClassesForKeeper' (type 'AndroidTestVariantClasspathJar').
  - Gradle detected a problem with the following location: '/<project_path>/feature/foo/domain/build/libs/domain-test-fixtures.jar'.

    Reason: Task ':app:jarStageReleaseTestAndroidTestClassesForKeeper' uses this output of task ':feature:foo:domain:testFixturesJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':feature:foo:domain:testFixturesJar' as an input of ':app:jarStageReleaseTestAndroidTestClassesForKeeper'.
      2. Declare an explicit dependency on ':feature:foo:domain:testFixturesJar' from ':app:jarStageReleaseTestAndroidTestClassesForKeeper' using Task#dependsOn.
      3. Declare an explicit dependency on ':feature:foo:domain:testFixturesJar' from ':app:jarStageReleaseTestAndroidTestClassesForKeeper' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/<project_path>/feature/components/bar/domain/build/libs/domain-test-fixtures.jar'.

    Reason: Task ':app:jarStageReleaseTestAndroidTestClassesForKeeper' uses this output of task ':feature:components:bar:domain:testFixturesJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':feature:components:bar:domain:testFixturesJar' as an input of ':app:jarStageReleaseTestAndroidTestClassesForKeeper'.
      2. Declare an explicit dependency on ':feature:components:bar:domain:testFixturesJar' from ':app:jarStageReleaseTestAndroidTestClassesForKeeper' using Task#dependsOn.
      3. Declare an explicit dependency on ':feature:components:bar:domain:testFixturesJar' from ':app:jarStageReleaseTestAndroidTestClassesForKeeper' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

There's about 10 of these failures in total, for different modules. I have two workarounds:
 - add explicit dependencies in the `app` module to the offending modules test fixtures
 - make the dependencies to offending modules `api` and not `implementation` in some other modules on which `app` depends

Not going into details because as you can imagine, there's lots of various dependencies everywhere — I can share more private details like `:dependencies` output on Slack. I also tried creating a simple repro with just some transitive modules and test fixtures without success.

I should note that some of the offending modules don't even have `testFixtures` sources.

So, at this point I'm mostly asking if this looks like something _obvious_ from your end — it feels like since the app compiles without issues, Keeper should be able to do its magic as well. Or maybe you have a hunch about what could be the culprit here so I have a more concrete steps to try to reproduce this in a sample project.

Thanks!
</div>

**Comment by ZacSweers** [comment]
I'm inclined to say this is an AGP or KGP bug, or possibly even Gradle itself. Keeper doesn't know anything about the incoming jars' origin tasks, all we do is point at AGP's API: https://github.com/slackhq/keeper/blob/f39acfcf5babc5b87a4597d2eaa889c0397b6905/keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt#L406-L409

Can I ask you to file an issue on AGP's issue tracker to start? We can reopen this if it's an issue with Keeper, but nothing I'm seeing suggests it.

**Comment by mateuszkwiecinski** [comment]
I'm trying to narrow down the issue, and I stumbled upon this piece of code: https://github.com/slackhq/keeper/blob/f39acfcf5babc5b87a4597d2eaa889c0397b6905/keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt#L365

`git blame` led me to https://github.com/slackhq/keeper/commit/5b9d59cccf2d9b38e204f8919fdb4be6c01ef5c8 and then https://issuetracker.google.com/issues/269089136#comment2 which sounds _familiar_ but isn't exactly the same issue, is it? 

I played with the code a bit, and surprisingly discovered that commenting out this very line: https://github.com/slackhq/keeper/blob/f39acfcf5babc5b87a4597d2eaa889c0397b6905/keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt#L368 allows the reproducer project compile. 
I tried to find what is the content of the collection, but the result I get is empty list + an error:
```
Execution failed for task ':repro:app:minifyReleaseWithR8'.
> Could not resolve all files for configuration ':repro:app:releaseAndroidTestRuntimeClasspath'.
   > Failed to transform ui-testing-test-fixtures.jar (project :repro:ui-testing) to match attributes {artifactType=android-filtered-proguard-rules, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=11, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Value for ExtractProGuardRulesTransform has not been calculated yet.
```

I filed the issue at https://issuetracker.google.com/issues/281669781, and the _interesting_ part, worth mentioning here is a separate invocation of: 
- `./gradlew jarReleaseAndroidTestClassesForKeeper` - completes successfully
- `./gradlew inferReleaseAndroidTestKeepRulesForKeeper` (which consumes  `jarReleaseAndroidTestClassesForKeeper` output) - also completes successfully
- `./gradlew minifyReleaseWithR8` - fails with error message pointing at `jarReleaseAndroidTestClassesForKeeper` misconfiguration 🤪
