### ISSUE TITLE
Update R8 version to latest stable AGP

### ISSUE THREAD

**Issue by lwasyl** [slackhq/keeper#129]
Opening just to have a reference link, new R8 contains some fixes for JDK21 support (https://issuetracker.google.com/issues/301353342). Overriding the version with `keeperR8("com.android.tools:r8:8.2.38")` resolves the issue

**Comment by ZacSweers** [comment]
Wanna send a PR?

**Comment by lwasyl** [comment]
https://github.com/slackhq/keeper/pull/130

**Comment by ZacSweers** [comment]
Fixed in #130
