### ISSUE TITLE
Crash building with FAIL_ON_PROJECT_REPOS config

### ISSUE THREAD

**Issue by jramism** [slackhq/keeper#136]
**Keeper version:** 0.15.0

#### Steps to reproduce:

1. Use settings.gradle to configure repos
2. Set in dependencyResolutionManagement -> repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
3. Include keeper plugin
4. Run build

#### Expected result:

Build successfully

#### Actual result:

Crash when running tests:

   > Build was configured to prefer settings repositories over project repositories but repository 'R8 releases repository for use with Keeper' was added by plugin 'com.android.internal.application'

**Comment by ZacSweers** [comment]
Please see the docs: https://slackhq.github.io/keeper/configuration/#custom-r8-behavior

**Comment by jramism** [comment]
Sorry for bothering, didn't see automaticR8RepoManagement.

Thanks!
