### ISSUE TITLE
Supply your own rules that will always be added to generated file

### ISSUE THREAD

**Issue by oheyadam** [slackhq/keeper#139]
I honestly don't know why 🤷‍♂️, but for some reason, Keeper hasn't been generating a comprehensive list of rules for us, so we've had to add some rules manually to our proguard rules file to make our tests stop failing at runtime, but of course this means these rules are also applied to our actual release APK. 

Since Keeper wires into R8 and supplies a generated rules file, I was wondering if we can maybe add a list/file property to the keeper extension that takes in custom rules that are always appended to whatever Keeper generates before supplying the final result to R8?

I'd be happy to take a stab at implementing this and opening a PR if you think this is fine

**Comment by ZacSweers** [comment]
I think it'd be better to just do that separately since it's ultimately not related to keeper. Either that or fix the underlying issue that causes the need for them. I don't think it'd be good to use keeper as a general proguard rules wiring tool
