### ISSUE TITLE
Unable to configure keeper plugin properly

### ISSUE THREAD

**Issue by karadkar** [slackhq/keeper#19]
**Keeper version:** 0.1.0

I'm not able to configure the keeper plugin. My minified apps androidTest still fails to compile.
I couldn't write androidTest in [keeprs sample app](https://github.com/slackhq/keeper/tree/master/sample) so attaching my separate project to reproduce this problem. Please help me with the configuration.

#### Steps to reproduce:

1. download and open the sample app in Studio.
2. set active build variant to `release`
3. run ExampleInstrumentedTest

#### Expected result:

Test should pass for minified release build

#### Actual result:

Test fails to compile for minifies release build

#### Attachments:
[keeper-compilation-issue-log.txt](https://github.com/slackhq/keeper/files/4139199/keeper-compilation-issue-log.txt)
[sample-app.zip](https://github.com/slackhq/keeper/files/4139398/sample-app.zip)

**Comment by ZacSweers** [comment]
This isn't a keeper issue, it's correctly generating rules.

```proguard
-keep enum androidx.lifecycle.Lifecycle$State {
  public static androidx.lifecycle.Lifecycle$State[] values();
  androidx.lifecycle.Lifecycle$State CREATED;
  androidx.lifecycle.Lifecycle$State DESTROYED;
  androidx.lifecycle.Lifecycle$State RESUMED;
  androidx.lifecycle.Lifecycle$State STARTED;
}
-keep class kotlin.jvm.internal.Intrinsics {
  public static void checkExpressionValueIsNotNull(java.lang.Object,java.lang.String);
}

```

This is a general R8 usage issue, and you'll need to figure that out for yourself! Keeper will never make an R8 minification task fail as all it does is generate extra rules, which are in turn generated from an R8 API!

**Comment by karadkar** [comment]
Okay thanks I'll look into that.

**Comment by karadkar** [comment]
@ZacSweers
Can you please help me add an example AndroidTest in keepers sample app?
Test which runs across all variants and fails if keeper plugin is removed!
Hope it makes sense

**Comment by ZacSweers** [comment]
Our current sample partially does this, but we’re working on porting the structure in our functional test to the sample. Please also file a separate issues for requests like this since that’s unrelated to this issue.

**Comment by karadkar** [comment]
Will do
