### ISSUE TITLE
zipflinger IllegalStateException: Too many entries - regression in 0.3 version

### ISSUE THREAD

**Issue by eugene-krivobokov** [slackhq/keeper#38]
**Keeper version:** 0.3.0, 0.3.1

Hi! We use keeper in a [small public project](https://github.com/avito-tech/avito-android/blob/develop/subprojects/android-test/test-app/build.gradle.kts) and in a huge private repository. The settings are completely the same:
```gradle
app/build.gradle:

plugins {
    id("com.slack.keeper") version "0.2.0"
}

keeper {
    automaticR8RepoManagement = false
    variantFilter {
        setIgnore(name != "stagingAutoTest")
    }
}

android {
  buildTypes {
    stagingAutoTest {}
  }
}

dependencies {
    keeperR8("com.android.tools:r8:1.6.89") // I've tried different ones just in case
}
```
After updating to 0.3.0 we've faced with the problem:

```
Caused by: java.lang.IllegalStateException: Too many entries (69585)
  	at com.android.zipflinger.ZipArchive.checkNumEntries(ZipArchive.java:212)
  	at com.android.zipflinger.ZipArchive.writeArchive(ZipArchive.java:181)
  	at com.android.zipflinger.ZipArchive.closeWithInfo(ZipArchive.java:166)
  	at com.android.zipflinger.ZipArchive.close(ZipArchive.java:155)
    ...
```

`app/build/intermediates/keeper/` directory is empty

I can't reproduce it on a small project. With 0.2.0 it works.

#### Steps to reproduce:

`./gradlew jar<build variant>ClassesForKeeper`

Is it a known limitation? Do we have any workaround?

**Comment by ZacSweers** [comment]
Thanks for the report! We'll take a look

**Comment by ZacSweers** [comment]
Looks like zipflinger doesn't support Zip64 after all :/. I've pinged the maintainers, but worst case we can look at adding a configuration for Zip64 support with the standard zip implementation (albeit it will be slower)

**Comment by ZacSweers** [comment]
CC @fabiensanglard in case you have any thoughts

**Comment by fabiensanglard** [comment]
The latest version of zipflinger does support zip64. What version are you using?

**Comment by ZacSweers** [comment]
We're using 3.6.1 (presumably bumped to 3.6.3 transitively by AGP in most projects). When I look in sources in the IDE, I still see TODOs for adding it

For this specific error, it originates from here:

![image](https://user-images.githubusercontent.com/1361086/81466318-a65a0880-919e-11ea-9ad1-be14d490eefb.png)

**Comment by fabiensanglard** [comment]
I see. The latest version of Zipflinger has not made it to AOSP yet. Let me check with AGP people to provide you with a release estimate.

**Comment by ZacSweers** [comment]
Sounds good, thanks!

**Comment by fabiensanglard** [comment]
It seems to be available in Android Studio 4.1 Canary which has AGP 4.0. I cannot commit on when it will be released in Stable.

**Comment by ZacSweers** [comment]
Nice, I see it when I try to update. I think what we can try to do is just shade in zipflinger only and use a newer version. We're already using internal AGP APIs, so not terribly worried about using non-stable dependencies as long as it's not forced on consumers. Will tinker with it a bit

**Comment by ZacSweers** [comment]
Folding the shading into #39
