### ISSUE TITLE
Publish the plugin to the Gradle Plugin Portal

### ISSUE THREAD

**Issue by eugene-krivobokov** [slackhq/keeper#41]
Hi! 
It would be great to see the plugin in [Gradle Plugin Portal](https://plugins.gradle.org/)

https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/

As far as I know, it's a common and convenient place for Gradle plugins.

**Comment by eugene-krivobokov** [comment]
Also, at this moment 0.3.2 version is the last version in [jcenter](https://bintray.com/bintray/jcenter/com.slack.keeper%3Akeeper)
Am I missing something?

**Comment by ZacSweers** [comment]
sigh, I thought I finally fixed the 0.4.0 release last night. Will look into it. As for the plugin portal, we already publish to mavencentral (which is the conventional repository for JVM OSS), what benefit does publishing to the plugin portal offer?

**Comment by eugene-krivobokov** [comment]
Thank you, jcenter will work for me.

As for Gradle Plugin Portal, I've asked in [Gradle slack](https://gradle-community.slack.com/archives/CA745PZHN/p1589564439336300). Please, take a look.

**Comment by ZacSweers** [comment]
Talked more there, opting to close this for now as I don't find the pros (no repo configuration needed) worth the cost of maintaining two distributions

**Comment by ZacSweers** [comment]
I've published 0.4.1 now, should be available within the next hour or so. The problem last night was that it only partially worked, so the marker uploaded succeeded but the rest did not 🤦
