### ISSUE TITLE
Rules are not generated for code in com.android.library modules on AGP 4.0-rc01

### ISSUE THREAD

**Issue by colinrtwhite** [slackhq/keeper#45]
**Keeper version:** 0.4.3

#### Steps to reproduce:

1. Download the [reproduction sample](https://github.com/slackhq/keeper/files/4693590/MyApplication.zip).
2. Generate the debug APK (`./gradlew clean assembleDebug`).
3. Take a look at the inferred rules in `app/build/intermediates/keeper`. On AGP 3.6.3 there will be this rule:

```kotlin
-keep class com.test.library.AndroidLibraryClass {
  public <init>();
  public void doSomethingCool();
}
```

However, it's missing on AGP 4.0.0-rc01 as `com.test.library.AndroidLibraryClass` is in a separate Android library module.

#### Expected result:

Keeper should generate a keep rule for `com.test.library.AndroidLibraryClass` as it's referenced from a `com.android.application` module's test sources.

#### Actual result:

Keeper does not generate any rules for `com.android.library` classes.

#### Attachments:

[Sample project](https://github.com/slackhq/keeper/files/4693590/MyApplication.zip)

**Comment by colinrtwhite** [comment]
I'm unable to create a sample project that reproduces the issue (not for lack of trying) so I'm going close this and try to work around the issue locally with manual keep rules. I'm not convinced it's completely related to generated code since there are a few missing rules for non-generated code.

**Comment by colinrtwhite** [comment]
Okay I figured out the cause and updated this issue with a sample project!

**Comment by ZacSweers** [comment]
Awesome! Will look soon
