### ISSUE TITLE
Cannot mutate content repository descriptor 'Google' after the repository has been used

### ISSUE THREAD

**Issue by parahall** [slackhq/keeper#52]
**Keeper version:** 0.3.1

Using 0.3.1 failing with "Cannot mutate content repository descriptor 'Google' after the repository has been used"

#### Steps to reproduce:

1. com.android.tools.build:gradle:3.6.3
2. gradle plugin: 6.5
3. Android Studio 4.0

#### Expected result:

Build successful

#### Actual result:

Gradle build failed: 
* What went wrong:
Could not determine the dependencies of task ':app:minifyMondayStagingWithR8'.
> Could not create task ':app:inferMondayStagingAndroidTestKeepRulesForKeeper'.
   > Cannot mutate content repository descriptor 'Google' after repository has been used

Thanks, Zack for help :)

**Comment by ZacSweers** [comment]
0.3.2 fixes this, but we're up to 0.5.0. Can you update your version?

**Comment by parahall** [comment]
It fixed the issue. Didn't noticed that 0.5 is out :)
