### ISSUE TITLE
Support to DexGuard?

### ISSUE THREAD

**Issue by dustinsummers** [slackhq/keeper#55]
Just curious if you all would be interested in creating a DexGuard Variant of this library?  Today, this does not work with DexGuard, primarily because of this line here...
```
          if (!appVariant.buildType.isMinifyEnabled) {
```
DexGuard handles the enabling of itself under the hood when you do `apply plugin <dexguard>`.  If it detects that `minifyEnabled` is set, it will throw an error when attempting to sync the project.

I think if this line were to change to something like
```
      if(!appVariant.buildType.isMinifyEnabled && 
         !pluginManager.withPlugin("<dexguard>"))
```
this library would be able to continue on as normal.

Thoughts?  If you need assistance writing this/testing it out, I'm more than happy to.

**Comment by ZacSweers** [comment]
We don't use DexGuard but would welcome a PR for supporting it if it can fit in the same we have. May require abstracting how we add our generated file to a specific task's inputs, but that's fine as long as it's not exorbitantly complicating.

Minor nit: `pluginManager.withPlugin("<dexguard>")` doesn't return a boolean, but rather accepts an action that's lazily called when the target plugin is applied.

**Comment by dustinsummers** [comment]
Great!  I will start work towards this 👍

**Comment by ZacSweers** [comment]
Sounds good, let us know if we can advise on anything. You might find some luck in the bugsnag gradle plugin for examples, but it's a little out of date I think as far as modern gradle APIs: https://github.com/bugsnag/bugsnag-android-gradle-plugin/search?q=dexguard&unscoped_q=dexguard

**Comment by ZacSweers** [comment]
We're actually going to drop support for proguard, which I think will rule out supporting this too. Happy to discuss further if it can be standalone, but AGP itself will be dropping proguard support
