### ISSUE TITLE
Variant Filter is always doing setIgnore(true) unless I explicitly set setIgnore(false)

### ISSUE THREAD

**Issue by colintheshots** [slackhq/keeper#60]
**Keeper version:** 0.6.0

Good bug reports include a failing test! Writing a test helps you to isolate and describe the
problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps
are likely to be closed.

#### Steps to reproduce:

1. Start with a Kotlin DSL build file. build.gradle.kts.
2. Add a variant filter as described in the documentation.

```
keeper {
    variantFilter {
        if (!buildType.isMinifyEnabled) {
            setIgnore(true)
        }
    }
}
```

3. Run minified release buildType tests that will break if classes are stripped without Keeper.
4. Tests break.
5. Change code to:

```
keeper {
    variantFilter {
        if (!buildType.isMinifyEnabled) {
            setIgnore(true)
        } else {
            setIgnore(false) // should be false by default, but is not
            // could also avoid the if statement and just say setIgnore(!buildType.isMinifyEnabled)
        }
    }
}
```
6. Run minified release buildType tests again.
7. Tests succeed and logic works as expected.

#### Expected result:

What you expected to happen: The variant filter should work as described in the documentation. setIgnore should be false by default.

#### Actual result:

What actually happened: SetIgnore was false by default until I added a variantFilter and a call to setIgnore. Then it seemed to become true by default.

#### Attachments:

![Cat is broken](https://media.giphy.com/media/8zFzUSzVZr7X2/giphy.gif)

**Comment by jschear** [comment]
Fixed in #61
