### ISSUE TITLE
Could not create task :app:inferDebugAndroidTestKeepRulesForKeeper

### ISSUE THREAD

**Issue by NoNews** [slackhq/keeper#94]
Hi, it's not a bug, probably just configuration question.

Trying to build hello world sample, but I've got an error: 
```
Could not create task ':app:inferDebugAndroidTestKeepRulesForKeeper
   > Build was configured to prefer settings repositories over project repositories but repository 'R8 releases repository for use with Keeper' was added by plugin 'com.slack.keeper'

```

P.S. in real project also would like to not create an additional build type and resolve everything by build params. Would it be possible with Keeper?

Thank you!

**Keeper version:** 0.11.1

#### Steps to reproduce:

1. `./gradlew app:assembleDebug` 

#### Expected result:

Build succeed

#### Actual result:

```
> Could not create task ':app:inferDebugAndroidTestKeepRulesForKeeper'.
   > Build was configured to prefer settings repositories over project repositories but repository 'R8 releases repository for use with Keeper' was added by plugin 'com.slack.keeper'
```

#### Versions
AGP 7.0.2
Kotlin 1.5.20
Keeper 0.11.1

#### build.gradle

```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.slack.keeper'
}

android {
.....
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            testProguardFile('test-rules.pro')
        }

    }

    keeper {
        automaticR8RepoManagement = true
        variantFilter {
            setIgnore(name != "debug")
        }
        emitDebugInformation = true
    }
}

.....

```

**Comment by ZacSweers** [comment]
As the error says, you have repositories controlled via your settings.gradle and that prohibits adhoc addition of other repositories later. You will need to either disable `automaticR8RepoManagement` or loosen the repo restriction in your project.

> P.S. in real project also would like to not create an additional build type and resolve everything by build params. Would it be possible with Keeper?

I don't really understand the question. Feel free to elaborate but please use discussions rather than the issue tracker for usage questions, thanks!
