### ISSUE TITLE
Use new ArtifactCollection APIs in a future gradle version

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/keeper#96]
https://github.com/gradle/gradle/pull/18729 should unlock some things for us where we're currently using internal properties

**Comment by eskatos** [comment]
gradle/gradle#18729 won't be in 7.4, it needs more work and is being reverted for now in https://github.com/gradle/gradle/pull/19119.

**Comment by ZacSweers** [comment]
Got it, thanks
